#!/usr/bin/env bash

###########################################
#                                         #
#      Charlatan Configuration            #
#      @543hn                             #
#                                         #
###########################################

##################
# GLOBAL CONFIG  #
##################

number_of_teams=2
number_of_images=2
competition_duration=60 # duration of competition in seconds

################
# TEAM CONFIG  #
################

team1_name="Byte Sized Falcons"
team1_ip="192.168.1."

team2_name="CyberD3lta"
team2_ip="192.168.1."

################
# IMAGE CONFIG #
################

image1="samoas" 
image1_ip="128"
image1_services=("ssh_22" "http_80") 
 
image2="dosidos" 
image2_ip="128"
image2_services=("https_443") 



# Injects
# todo
